{"body": "<p>It seems that you have set a weird character somewhere, most likely in the name of the sqlite file specified in django settings.</p>\n\n<p>Django dies trying to do <code>raise MigrationSchemaMissing(\"Unable to create the django_migrations table (%s)\" % exc)</code> - when doing this it encounters the UNICODE error which tells that 0xf1 is not part of ASCII. Based on <a href=\"http://www.theasciicode.com.ar/extended-ascii-code/plus-minus-sign-ascii-code-241.html\" rel=\"nofollow\">this table</a> this is the character <code>\u00b1</code>. As django will definetly not use this as a table name, i guess it must be related to the filename.</p>\n\n<p>If this is not the case try <code>grep '\u00b1' .</code> inside of your project folder to find the usage of this character. HTH</p>\n", "tags": ["django", "sqlite3"], "creation_date": 1476801657, "score": 0, "last_activity_date": 1476801657, "answer_id": 40111240, "is_accepted": false, "owner": {"user_id": 5992118, "reputation": 839, "user_type": "registered", "display_name": "dahrens", "link": "http://stackoverflow.com/users/5992118/dahrens", "profile_image": "https://www.gravatar.com/avatar/08ae2e7ce567cbfb93d480892bd10fa0?s=128&d=identicon&r=PG"}, "title": "I am facing to start runserver django?", "question_id": 40110505}