{"body": "<p>Make sure your using the latest version chromedriver:\n<a href=\"http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip\" rel=\"nofollow\">http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip</a></p>\n\n<p>I installed chromedriver 2.0 and got this error,</p>\n\n<p>when i upgraded to 2.25 it got rid of this error.</p>\n\n<p>Good luck :)</p>\n", "tags": ["python", "selenium", "selenium-chromedriver", "httplib"], "creation_date": 1477597785, "score": 1, "last_activity_date": 1477597785, "answer_id": 40293101, "is_accepted": false, "owner": {"user_id": 4539241, "reputation": 21, "user_type": "registered", "display_name": "Kirk Douglas Jr", "link": "http://stackoverflow.com/users/4539241/kirk-douglas-jr", "profile_image": "https://www.gravatar.com/avatar/c01072fd8d0930487bcb0251abd0e6b3?s=128&d=identicon&r=PG&f=1"}, "title": "Selenium 2.53.5 httplib.BadStatusLine: &#39;&#39; Python", "question_id": 40286393}