{"body": "<p>Despite a lot of tests still at square one with this asynchronous data transfer. I'm completely sure my request is good. The good news is that handling the LibUsb.handleEventTimeOut the callback function of the interrupt transfer is called ... when its timeout arrives....</p>\n\n<p>This is puzzling because  the command used on windows with driverWizard works perfectly fine. Also I think it should be possible to do it with my current configuration on the Raspberry with LibUsb since synchronous transfers with the device ( get descriptor, configuration ...) work fine. Also even if the control callback is never called ( probably since the device sends nothing back on control pipe) it ends with a TIMEOUT with the good command, while it's an error 9 \" invalid command\" with a slightly different command ... it's a good sign I think, it shows the device react at least a little to the command. </p>\n\n<p>But i'm afraid to be out of idea. Could this be : </p>\n\n<ul>\n<li>an incompatibility due to LibUsb/Raspberry that makes asynchronous transfer unhandable ? I don't know if raspberry usb capabilities include asynchronous transfers ( but it seems probable, since without it a lot of device couldn't work with raspberry ! )</li>\n<li>a problem with the way LibUsb handle asynchronous transfer ? if the device react a little to the command it should write in pipe 0x81 triggering the interrupt transfer completion event, no ? That's exactly what is dne with the pipe listening in DriverWizard even though i don't know how it does exactly.</li>\n</ul>\n\n<p>I'm open ot every ideas right now ! I'll still give some tries next week but if it doesn't work i'll have forget this particular thermometer.<br>\nBy the way do you know thermometers/hygrometers easily configurable on raspberry and allowing time real (every minutes) measures and data transfer ? </p>\n", "tags": ["linux", "libusb", "libusb-1.0"], "creation_date": 1477694739, "score": 0, "last_activity_date": 1477694739, "answer_id": 40314187, "is_accepted": false, "owner": {"user_id": 7069713, "reputation": 1, "user_type": "registered", "display_name": "Belze88", "link": "http://stackoverflow.com/users/7069713/belze88", "profile_image": "https://lh3.googleusercontent.com/-PdL811Yv52M/AAAAAAAAAAI/AAAAAAAAAEw/71LAt1C0U2A/photo.jpg?sz=128"}, "title": "USB error 9 during control transfer", "question_id": 40241304}