{"tags": ["python", "flask", "sqlalchemy", "python-social-auth"], "is_answered": false, "creation_date": 1475938538, "view_count": 69, "score": 1, "last_activity_date": 1477685292, "title": "python-social-auth: AttributeError: &#39;SQLAlchemy&#39; object has no attribute &#39;query&#39; on /complete/vk-oauth2 url", "answer_count": 1, "owner": {"user_id": 2111562, "reputation": 87, "user_type": "registered", "accept_rate": 86, "display_name": "Meatbot", "link": "http://stackoverflow.com/users/2111562/meatbot", "profile_image": "https://www.gravatar.com/avatar/2231a990c0149e7a5730bd09d2a51365?s=128&d=identicon&r=PG"}, "link": "http://stackoverflow.com/questions/39933816/python-social-auth-attributeerror-sqlalchemy-object-has-no-attribute-query", "question_id": 39933816}