{"tags": ["python-2.7", "subprocess", "child-process", "sigsegv", "signal-handling"], "is_answered": false, "creation_date": 1477733898, "view_count": 18, "score": 2, "last_activity_date": 1477804338, "title": "Handling segmentation fault due to a C++ subprocess spawned by Python code", "answer_count": 1, "owner": {"user_id": 6554518, "reputation": 22, "user_type": "registered", "display_name": "Shashank shet", "link": "http://stackoverflow.com/users/6554518/shashank-shet", "profile_image": "https://www.gravatar.com/avatar/9580093f9c70f1a19fe00669c0ce75c1?s=128&d=identicon&r=PG&f=1"}, "link": "http://stackoverflow.com/questions/40317792/handling-segmentation-fault-due-to-a-c-subprocess-spawned-by-python-code", "question_id": 40317792}