{"tags": ["python", "amazon-s3", "databricks"], "is_answered": false, "creation_date": 1477612154, "view_count": 11, "score": 0, "last_activity_date": 1477684913, "title": "Unable to save the correct file format to S3 using Databricks (python)", "answer_count": 1, "owner": {"user_id": 1643537, "reputation": 867, "user_type": "registered", "accept_rate": 83, "display_name": "Cryssie", "link": "http://stackoverflow.com/users/1643537/cryssie", "profile_image": "https://www.gravatar.com/avatar/05f10817c94446e3719601c258652df5?s=128&d=identicon&r=PG"}, "link": "http://stackoverflow.com/questions/40295927/unable-to-save-the-correct-file-format-to-s3-using-databricks-python", "question_id": 40295927}